"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.findAllUserUseCase = exports.deleteUserUseCase = exports.updateUserUseCase = exports.findUserUseCase = exports.createUserUseCase = void 0;
const repositories_1 = require("@/repositories");
const createUser_useCase_1 = require("./createUser.useCase");
const findUser_useCase_1 = require("./findUser.useCase");
const updateUser_useCase_1 = require("./updateUser.useCase");
const deleteUser_useCase_1 = require("./deleteUser.useCase");
const findAllUsers_useCase_1 = require("./findAllUsers.useCase");
const createUserUseCase = new createUser_useCase_1.CreateUserUseCase(repositories_1.userRepo);
exports.createUserUseCase = createUserUseCase;
const findUserUseCase = new findUser_useCase_1.FindUserUseCase(repositories_1.userRepo);
exports.findUserUseCase = findUserUseCase;
const updateUserUseCase = new updateUser_useCase_1.UpdateUserUseCase(repositories_1.userRepo);
exports.updateUserUseCase = updateUserUseCase;
const deleteUserUseCase = new deleteUser_useCase_1.DeleteUserUseCase(repositories_1.userRepo);
exports.deleteUserUseCase = deleteUserUseCase;
const findAllUserUseCase = new findAllUsers_useCase_1.FindAllUsersUseCase(repositories_1.userRepo);
exports.findAllUserUseCase = findAllUserUseCase;
